"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { projectFormSchema, type ProjectFormValues } from "./schemas";
import type { ActionResult } from "@/lib/action-result";
const refresh = () => { revalidatePath("/projects"); revalidatePath("/dashboard"); revalidatePath("/tasks"); };
function normalize(values: ProjectFormValues) { const parsed = projectFormSchema.safeParse(values); if (!parsed.success) return { ok:false as const, message:"Please check the project fields." }; return { ok:true as const, data:{ name:parsed.data.name, description:parsed.data.description?.trim()||null, status:parsed.data.status, priority:parsed.data.priority, progress:Number(parsed.data.progress), next_action:parsed.data.next_action?.trim()||null, blocker:parsed.data.blocker?.trim()||null, github_url:parsed.data.github_url||null, live_url:parsed.data.live_url||null, notes:parsed.data.notes?.trim()||null, milestones:parsed.data.milestones ?? [] } }; }
export async function createProjectAction(values: ProjectFormValues): Promise<ActionResult> { const user=await requireUser(); const n=normalize(values); if(!n.ok)return n; const supabase=await createClient(); const {data:project,error}=await supabase.from("projects").insert({user_id:user.id,...n.data.milestones && (()=>{const {milestones,...rest}=n.data;return rest;})()}).select("id").single(); if(error||!project)return {ok:false,message:error?.message||"Could not create project."}; if(n.data.milestones.length) await supabase.from("project_milestones").insert(n.data.milestones.map((m,i)=>({project_id:project.id,user_id:user.id,title:m.title,is_complete:m.is_complete,position:i,due_date:m.due_date||null}))); refresh(); return {ok:true,message:"Project created."}; }
export async function updateProjectAction(id:string,values:ProjectFormValues):Promise<ActionResult>{const user=await requireUser();const n=normalize(values);if(!n.ok)return n;const supabase=await createClient();const {milestones,...projectData}=n.data;const {error}=await supabase.from("projects").update(projectData).eq("id",id).eq("user_id",user.id);if(error)return{ok:false,message:error.message};await supabase.from("project_milestones").delete().eq("project_id",id).eq("user_id",user.id);if(milestones.length)await supabase.from("project_milestones").insert(milestones.map((m,i)=>({project_id:id,user_id:user.id,title:m.title,is_complete:m.is_complete,position:i,due_date:m.due_date||null})));refresh();return{ok:true,message:"Project updated."};}
export async function deleteProjectAction(id:string):Promise<ActionResult>{const user=await requireUser();const supabase=await createClient();const{error}=await supabase.from("projects").delete().eq("id",id).eq("user_id",user.id);if(error)return{ok:false,message:error.message};refresh();return{ok:true,message:"Project deleted."};}
