"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import type { ActionResult } from "@/lib/action-result";
import { moduleFormSchema, studySessionSchema, type ModuleFormValues, type StudySessionValues } from "./schemas";
const jsonArray=(value?:string)=>{if(!value?.trim())return[];try{const parsed=JSON.parse(value);return Array.isArray(parsed)?parsed:[]}catch{return value.split("\n").map(v=>v.trim()).filter(Boolean).map(title=>({title,date:""}));}};
const refresh=()=>{revalidatePath("/university");revalidatePath("/dashboard");};
export async function createModuleAction(values:ModuleFormValues):Promise<ActionResult>{const user=await requireUser();const p=moduleFormSchema.safeParse(values);if(!p.success)return{ok:false,message:"Please check the module fields."};const supabase=await createClient();const{error}=await supabase.from("modules").insert({user_id:user.id,name:p.data.name,code:p.data.code?.trim()||null,lecturer:p.data.lecturer?.trim()||null,schedule:jsonArray(p.data.schedule),current_topic:p.data.current_topic?.trim()||null,confidence_level:Number(p.data.confidence_level),notes:p.data.notes?.trim()||null,assignment_deadlines:jsonArray(p.data.assignment_deadlines),exam_dates:jsonArray(p.data.exam_dates)});if(error)return{ok:false,message:error.message};refresh();return{ok:true,message:"Module created."};}
export async function updateModuleAction(id:string,values:ModuleFormValues):Promise<ActionResult>{const user=await requireUser();const p=moduleFormSchema.safeParse(values);if(!p.success)return{ok:false,message:"Please check the module fields."};const supabase=await createClient();const{error}=await supabase.from("modules").update({name:p.data.name,code:p.data.code?.trim()||null,lecturer:p.data.lecturer?.trim()||null,schedule:jsonArray(p.data.schedule),current_topic:p.data.current_topic?.trim()||null,confidence_level:Number(p.data.confidence_level),notes:p.data.notes?.trim()||null,assignment_deadlines:jsonArray(p.data.assignment_deadlines),exam_dates:jsonArray(p.data.exam_dates)}).eq("id",id).eq("user_id",user.id);if(error)return{ok:false,message:error.message};refresh();return{ok:true,message:"Module updated."};}
export async function deleteModuleAction(id:string):Promise<ActionResult>{const user=await requireUser();const supabase=await createClient();const{error}=await supabase.from("modules").delete().eq("id",id).eq("user_id",user.id);if(error)return{ok:false,message:error.message};refresh();return{ok:true,message:"Module deleted."};}
export async function logStudySessionAction(values:StudySessionValues):Promise<ActionResult>{const user=await requireUser();const p=studySessionSchema.safeParse(values);if(!p.success)return{ok:false,message:"Please check the study session fields."};const supabase=await createClient();const{error}=await supabase.from("study_sessions").insert({user_id:user.id,module_id:p.data.module_id,duration_minutes:Number(p.data.duration_minutes),topic:p.data.topic?.trim()||null,session_date:p.data.session_date,notes:p.data.notes?.trim()||null});if(error)return{ok:false,message:error.message};refresh();return{ok:true,message:"Study session logged."};}
