"use client";
import { useState, useTransition } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import type { ActionResult } from "@/lib/action-result";
import type { ModuleFormValues, StudySessionValues } from "./schemas";
export function ModuleForm({action}:{action:(v:ModuleFormValues)=>Promise<ActionResult>}){const[pending,start]=useTransition();const[result,setResult]=useState<ActionResult|null>(null);const[v,setV]=useState<ModuleFormValues>({name:"",code:"",lecturer:"",schedule:"",current_topic:"",confidence_level:"50",notes:"",assignment_deadlines:"",exam_dates:""});const set=(k:keyof ModuleFormValues,x:string)=>setV(a=>({...a,[k]:x}));return <form className="space-y-3" onSubmit={e=>{e.preventDefault();start(async()=>{const r=await action(v);setResult(r);if(r.ok)setV({...v,name:"",code:""});})}}><div className="grid gap-3 sm:grid-cols-2"><div><Label>Name</Label><Input value={v.name} onChange={e=>set("name",e.target.value)}/></div><div><Label>Code</Label><Input value={v.code} onChange={e=>set("code",e.target.value)}/></div><div><Label>Lecturer</Label><Input value={v.lecturer} onChange={e=>set("lecturer",e.target.value)}/></div><div><Label>Confidence (%)</Label><Input type="number" min="0" max="100" value={v.confidence_level} onChange={e=>set("confidence_level",e.target.value)}/></div></div><div><Label>Schedule</Label><Input placeholder="Mon 10:00, Wed 14:00" value={v.schedule} onChange={e=>set("schedule",e.target.value)}/></div><div><Label>Current topic</Label><Input value={v.current_topic} onChange={e=>set("current_topic",e.target.value)}/></div><div><Label>Assignment deadlines</Label><Textarea placeholder="One per line: Assignment 1 | 2026-09-01" value={v.assignment_deadlines} onChange={e=>set("assignment_deadlines",e.target.value)}/></div><div><Label>Exam dates</Label><Textarea placeholder="One per line: Final exam | 2026-12-10" value={v.exam_dates} onChange={e=>set("exam_dates",e.target.value)}/></div><div><Label>Notes</Label><Textarea value={v.notes} onChange={e=>set("notes",e.target.value)}/></div>{result?<p className={result.ok?"text-sm text-emerald-300":"text-sm text-rose-300"}>{result.message}</p>:null}<Button disabled={pending}>{pending?"Saving…":"Add module"}</Button></form>}
export function StudySessionForm({modules,action}:{modules:Array<{id:string;name:string}>;action:(v:StudySessionValues)=>Promise<ActionResult>}){const[pending,start]=useTransition();const[result,setResult]=useState<ActionResult|null>(null);const[v,setV]=useState<StudySessionValues>({module_id:modules[0]?.id??"",duration_minutes:"60",topic:"",session_date:new Date().toISOString().slice(0,10),notes:""});const set=(k:keyof StudySessionValues,x:string)=>setV(a=>({...a,[k]:x}));return <form className="space-y-3" onSubmit={e=>{e.preventDefault();start(async()=>{const r=await action(v);setResult(r);})}}><div><Label>Module</Label><select className="h-10 w-full rounded-md border border-zinc-800 bg-zinc-950 px-3 text-sm" value={v.module_id} onChange={e=>set("module_id",e.target.value)}>{modules.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></div><div className="grid gap-3 sm:grid-cols-2"><div><Label>Duration (minutes)</Label><Input type="number" min="1" value={v.duration_minutes} onChange={e=>set("duration_minutes",e.target.value)}/></div><div><Label>Date</Label><Input type="date" value={v.session_date} onChange={e=>set("session_date",e.target.value)}/></div></div><div><Label>Topic</Label><Input value={v.topic} onChange={e=>set("topic",e.target.value)}/></div><div><Label>Notes</Label><Textarea value={v.notes} onChange={e=>set("notes",e.target.value)}/></div>{result?<p className={result.ok?"text-sm text-emerald-300":"text-sm text-rose-300"}>{result.message}</p>:null}<Button disabled={pending||!modules.length}>{pending?"Logging…":"Log study session"}</Button></form>}
